### ISSUE TITLE
Wifi password

### ISSUE THREAD

**Issue by DartFPV** [IlyaDanilenko/geoscan_pioneer_max#1]
Нигде толком не могу найти информацию по работе с RaspberryPi на Пионере Макс, кроме нескольких отрывочных гайдов в этом хабе. Будет ли добавляться информация на pioneer-doc.readthedocs.io? Какие-то примеры проектов?

Где найти пароль на wifi сетку Geoscan после установки образа ubuntu на RaspberryPi?

**Comment by IlyaDanilenko** [comment]
Добрый день, информация обязательно будет добавляться на сайт документации Пионер. На данный момент все существующие гайды находятся в этом репозитории. Пионер Макс является новым продуктом, поэтому примеры проектов появятся не сразу, сейчас же Вы можете ознакомиться с (примерами кода)[https://github.com/IlyaDanilenko/gs_example]

Настройки Wi-fi находятся в каталоге /etc/hostapd/hostapd.conf, открыть файл можно с помощью встроенного текстового редактора nano

По умолчанию пароль: geoscan123

**Comment by DartFPV** [comment]
Спасибо. Будем ждать.

**Comment by DartFPV** [comment]
А логин/пароль для RPi? стандартные pi/raspberry не подходят. соответственно нет доступа к ssh.

**Comment by IlyaDanilenko** [comment]
Логин: ubuntu
Пароль: geoscan123

Подключение по ssh к RPi:
```ssh ubuntu@10.0.0.31```
Подключение по web-ssh к RPi: [инструкция](https://github.com/IlyaDanilenko/geoscan_pioneer_max/blob/master/guides/web-ssh.md)
Как войдете, выполните:
```source ~/.bashrc``` для активации среды. В будущем обновлении это будет происходить автоматически.

**Comment by IlyaDanilenko** [comment]
Для автоматической активации среды необходимо закинуть в /home/ubuntu/ файлы из этой [папки](https://drive.google.com/drive/folders/1B9xX6Lec-dHWj-v2Aa-duCcyRoBi-KTB?usp=sharing)

**Comment by IlyaDanilenko** [comment]
Вышел новый образ, в котором исправлена автоматическая активация среды
